version: "3" 
services:

  database:
    container_name: %s_database
    image: postgres:9.4
    env_file: .env
    volumes:
      - db-logs:/var/log/postgresql
      - db-data:/var/lib/postgresql/data

  website:
    container_name: %s_website
    build: .
    env_file: .env
    volumes:
      - ./website:/code/website
    depends_on:
      - database
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  proxy:
    container_name: %s_proxy
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static:/www/static
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - website
    links:
      - website

volumes:
  db-data:
  db-logs:
  static:
