version: '3'
services:
  database:
    image: postgres:9.4
    env_file: .env
    volumes:
      - /etc/postgresql
      - /var/log/postgresql
      - /var/lib/postgresql

  website:
    build: ./website
    volumes:
      - ./website:/code
    depends_on:
      - database
    env_file: .env
    expose:
      - "8000"
  proxy:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - /www/static
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - website
    depends_on:
      - website
    links:
      - website
