webapp:
  build: ./website
  volumes:
    - /code/static
    - /etc/localtime:/etc/localtime:ro
  env_file: .env

proxy:
  build: ./nginx
  ports:
    - "1338:80"
  volumes:
    - /www/static
    - /etc/localtime:/etc/localtime:ro

database:
  image: postgres:9.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - data
  env_file: .env

data:
  image: busybox
  volumes:
    - /etc/postgresql
    - /var/log/postgresql
    - /var/lib/postgresql

